-- 코드를 입력하세요
# SELECT REST_ID, MEMBER_ID, REVIEW_SCORE, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
SELECT A.REST_ID, A.REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM  (SELECT *
    FROM REST_INFO
    WHERE SUBSTRING(address,1,2) = '서울') A INNER JOIN REST_REVIEW B
ON A.REST_ID = B.REST_ID
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC


# SELECT REST_ID
#     FROM REST_INFO
#     WHERE SUBSTRING(address,1,2) = '서울'
