-- 코드를 입력하세요
select *
from (SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS AVERAGE_DURATION
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID) C
where AVERAGE_DURATION >= 7
order by AVERAGE_DURATION DESC, CAR_ID DESC