SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM 
(SELECT A.FISH_TYPE, B.FISH_NAME FROM FISH_INFO A  JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE  ) AS S
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC
