-- 코드를* 입력하세요
select A.FLAVOR
from FIRST_HALF A LEFT OUTER JOIN (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
FROM JULY
GROUP BY FLAVOR) B
ON A.FLAVOR = B.FLAVOR
ORDER BY TOTAL_ORDER + JULY_ORDER DESC
LIMIT 3

-- from FIRST_HALF A RIGHT OUTER JOIN JULY B ON A.SHIPMENT_ID = B.SHIPMENT_ID