-- 코드를 입력하세요
SELECT A.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM 
(
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) A LEFT OUTER JOIN FOOD_PRODUCT B
ON A.CATEGORY = B.CATEGORY AND A.MAX_PRICE = B.PRICE
WHERE A.CATEGORY IN ('과자','국', '김치','식용유')
ORDER BY MAX_PRICE DESC