SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (SELECT *, IFNULL(LENGTH, 10) AS new_length FROM FISH_INFO) AS sub_table
GROUP BY FISH_TYPE
HAVING AVG(new_length) >= 33
ORDER BY FISH_TYPE ASC